language: ruby
jdk:
  - oraclejdk7
  #- openjdk7
  #- openjdk6
rvm:
  - jruby-18mode
  - jruby-19mode
  - jruby-head
before_install:
  - export JRUBY_OPTS="--server -Xcext.enabled=false -Xcompile.invokedynamic=false"
